[toolchain]

[features]
seeds = false
skip-lint = false
[features.test-mode]
activate = true

[programs.localnet]
propertytoken = "DWfqXY9yuAEkU7MK2tcWxNGFqtuQyc2GMN64AmDebv8g"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"